### ISSUE TITLE
Change Base Text on Template to use Work Sans Font

### ISSUE THREAD

**Issue by kpwags** [kpwags/social-image-generator#4]
## Background
The Work Sans font is used to write the text to the image. It'd be nice for "Keith Wagner" and "@kpwags" to also use the same font

## Goal
Re-create the template using the Work Sans font

## Task

- [x] Replace the font with Work Sans
- [x] Ensure the text doesn't overlap
- [x] Replace the template
